FROM vastai/tensorflow as BUILDER

# install prerequisites
RUN apt-get update && apt-get install -y clang-6.0 ninja-build protobuf-compiler libprotobuf9v5 libprotobuf-dev
RUN pip3 install meson

# download and compile lc0
RUN     cd ~ && \
        git clone -b release/0.22 --recurse-submodules https://github.com/LeelaChessZero/lc0.git lc0 && \
        ./lc0/build.sh


# download and unpack stockfish
RUN apt-get install -y wget unzip && \
    cd ~ && \
    wget https://stockfishchess.org/files/stockfish-10-linux.zip && \
    unzip stockfish-10-linux.zip && \
    chmod +x /root/stockfish-10-linux/Linux/*

FROM vastai/tensorflow

RUN apt-get update && apt-get install -y libprotobuf9v5

# Copy scripts for network download and lc0 startup
WORKDIR /lc0
COPY ./scripts/* /lc0/
RUN chmod +x /lc0/* && \
    mkdir /lc0/weights
COPY --from=builder /root/lc0/build/release/lc0 .
ENV PATH /lc0:$PATH

# Copy stockfish executables
RUN mkdir /stockfish
COPY --from=builder /root/stockfish-10-linux/Linux/* /stockfish/
ENV PATH /stockfish:$PATH
