#!/usr/bin/env bash
## Script for setting and downloading network, mainly meant for vast.ai
## where environment variables cannot be set as easily

export NETWORK=$1

if [[ -z "$NETWORK" ]]
then
    echo "No network hash provided as argument"
    exit 1
else
    echo "$NETWORK" > /lc0/network
    /lc0/network_parse
fi
