
default:
  lc0_version: "0.22"
  tag_suffix: ""
  imagename: simske/lc0
  stockfish: False
  build:
    image: nvidia/cuda:10.1-cudnn7-devel
    apt_prerequisites: git ninja-build protobuf-compiler libprotobuf-dev python3 python3-pip
    python3_link: True

  runtime:
    image: nvidia/cuda:10.1-cudnn7-devel
    apt_prerequisites: libprotobuf10 wget
    shared_libraries:
     - /root/lc0/build/release/./subprojects/zlib-1.2.11/libz.so
    cmd: True

default_stockfish:
  base: default
  stockfish: True
  tag_suffix: _stockfish

vastai:
  base: default
  tag_suffix: _vastai
  build:
    image: vastai/tensorflow
    apt_prerequisites: git ninja-build libprotobuf9v5
    python3_link: False

  runtime:
    image: vastai/tensorflow
    apt_prerequisites: libprotobuf9v5
    shared_libraries: []
    cmd: False

vastai_stockfish:
  base: vastai
  tag_suffix: _stockfish_vastai
  stockfish: True
