
default:
  version_tag: "0.27"
  lc0_version: "0.27.0"
  tag_suffix: ""
  imagename: docker.io/simske/lc0
  stockfish: False
  march: ivybridge
  build:
    image: nvcr.io/nvidia/cuda:11.0.3-cudnn8-devel-ubuntu20.04
    apt_prerequisites: >-
        git
        wget
        unzip
        ninja-build
        python3
        python3-pip
        gcc-8
        g++-8
        libeigen3-dev
        clang
        libopenblas-dev
        cmake

  runtime:
    image: nvcr.io/nvidia/cuda:11.0.3-cudnn8-runtime-ubuntu20.04
    apt_prerequisites: >-
        wget
        libopenblas-base
    cmd: True

stockfish:
  base: default
  stockfish: True
  stockfish_url: https://stockfishchess.org/files/stockfish_14_linux_x64_avx2.zip
  tag_suffix: -stockfish
