
default:
  version_tag: "0.26"
  lc0_version: "0.26.0"
  tag_suffix: ""
  imagename: simske/lc0
  stockfish: False
  build:
    image: nvidia/cuda:10.0-cudnn7-devel
    apt_prerequisites: git wget unzip ninja-build python3 python3-pip gcc-8 g++-8 libeigen3-dev clang
    python3_link: True

  runtime:
    image: nvidia/cuda:10.0-cudnn7-runtime
    apt_prerequisites: wget
    shared_libraries:
     - /root/lc0/build/release/./subprojects/zlib-1.2.11/libz.so
    cmd: True

default_stockfish:
  base: default
  stockfish: True
  tag_suffix: -stockfish

vastai:
  base: default
  tag_suffix: -vastai

vastai_stockfish:
  base: vastai
  tag_suffix: -stockfish-vastai
  stockfish: True
