
default:
  version_tag: "0.26"
  lc0_version: "0.26.3"
  tag_suffix: ""
  imagename: simske/lc0
  stockfish: False
  march: ivybridge
  build:
    image: nvidia/cuda:11.0.3-cudnn8-devel-ubuntu20.04
    apt_prerequisites: >-
        git
        wget
        unzip
        ninja-build
        python3
        python3-pip
        gcc-8
        g++-8
        libeigen3-dev
        clang
        libopenblas-dev
        cmake

  runtime:
    image: nvidia/cuda:11.0.3-cudnn8-runtime-ubuntu20.04
    apt_prerequisites: >-
        wget
        libopenblas-base
    cmd: True

stockfish:
  base: default
  stockfish: True
  tag_suffix: -stockfish
