FROM vastai/tensorflow as BUILDER

# install prerequisites
RUN apt-get update && apt-get install -y clang-6.0 ninja-build libprotobuf9v5
RUN pip3 install meson

# download and compile lc0
RUN     cd ~ && \
        git clone -b release/0.22 --recurse-submodules https://github.com/LeelaChessZero/lc0.git lc0 && \
        ./lc0/build.sh


FROM vastai/tensorflow

RUN apt-get update && apt-get install -y libprotobuf9v5

WORKDIR /lc0
COPY --from=0 /root/lc0/build/release/lc0 .
ENV PATH /lc0:$PATH

# Copy scripts for network download and lc0 startup
WORKDIR /lc0
COPY ./scripts/* /lc0/
RUN chmod +x /lc0/* && \
    mkdir /lc0/weights
COPY --from=builder /root/lc0/build/release/lc0 .
ENV PATH /lc0:$PATH
